export const ARTIST_LIST_REQUEST = 'ARTIST_LIST_REQUEST';
export const ARTIST_LIST_SUCCESS = 'ARTIST_LIST_SUCCESS';
export const ARTIST_LIST_FAILURE = 'ARTIST_LIST_FAILURE';

export const ARTIST_REQUEST = 'ARTIST_REQUEST';
export const ARTIST_SUCCESS = 'ARTIST_SUCCESS';
export const ARTIST_FAILURE = 'ARTIST_FAILURE';

export const ALBUM_LIST_REQUEST = 'ALBUM_LIST_REQUEST';
export const ALBUM_LIST_SUCCESS = 'ALBUM_LIST_SUCCESS';
export const ALBUM_LIST_FAILURE = 'ALBUM_LIST_FAILURE';

export const TRACK_LIST_REQUEST = 'TRACK_LIST_REQUEST';
export const TRACK_LIST_SUCCESS = 'TRACK_LIST_SUCCESS';
export const TRACK_LIST_FAILURE = 'TRACK_LIST_FAILURE';

